---
title: "CLIF Change Log"
---

### Version History

### 2.2.0 
- **Release** TBD
- **Beta Status Updates** WIP


### 2.1.0
- **Release** September 2025
- **Data Structure Updates**
  - Move Code Status, CRRT therapy, ECMO MCS, Hospital Diagnosis, Microbiology Culture, and Micro non-culture to Beta status
  - Finalize patient language category mCIDE- [Issue#13](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/13)
  - Add ADT location type field with finalized mCIDE- [Issue#39](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/39), [Issue#64](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/64)
  - Finalize hospitalization admission type mCIDE- [Issue#16](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/16)
  - Add LTACH to hospital_type mCIDE
  - Revision to Micro culture mCIDE for LOINC compatibility - [Issue#25](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/25)
  - Finalize patient language category mCIDE - [Issue#13](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/13)
  - Add ADT location type field with finalized mCIDE - [Issue#39](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/39), [Issue#64](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/64)
  - Finalize hospitalization admission type mCIDE (Add LTACH to admission_type mCIDE) - [Issue#16](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/39)
  - Additional information on hospitalization variables for ADI/SVI
  - Addition of device_id to respiratory_support [Issue#67](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/67)

### 2.0.0 (Current Version)
- **Release** February 2025
- **Major ERD Upgrade**
  - Combined patient and hospitalization tables
  - Introduced maturity concept for ERD and tables
  - Added Beta tables and concept tables
  - Standardized mCIDE elements
  - Standardized all datetime variables to be time zone aware with UTC- [Issue#40](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/40)
  - Revision to Micro culture mCIDE for LOINC compatibility - [Issue#25](https://github.com/Common-Longitudinal-ICU-data-Format/CLIF/issues/25)

### 1.0.0
- First official release of CLIF
